services:
  web:
    build:
      context: .
      target: dev
      network: host
      args:
        PORT: ${PORT:-3000}
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ${MYFILES}:${MYFILES}
    environment:
      - WATCHPACK_POLLING=true
      - PORT=${PORT:-3000}
