services:
  web:
    build:
      context: .
      target: runner
      network: host
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - count-and-size-data:/app/data

volumes:
  count-and-size-data:
