services:
  web:
    build:
      context: .
      target: runner
      network: host
      args:
        PORT: ${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      - PORT=${PORT:-3000}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ${MYFILES}:${MYFILES}
