export interface RenamePlanCandidate {
  leftName: string;
  rightName: string;
}

export interface RenamePlanStep {
  /** A fixed, currently-real file name, OR a reference to an earlier
   * step's actual runtime result — only used for the final step of a
   * cycle-breaking sequence, whose source is a backup name generated by
   * that earlier step and not known ahead of time (see below). */
  sourceName: string | { dependsOnStepIndex: number };
  /** The real target name for a genuine match step; a human-readable
   * placeholder (e.g. "B.txt.<timestamp>.bk") for a backup step, since
   * the real timestamped name is only assigned when it actually runs. */
  destinationName: string;
  isBackup: boolean;
}

function backupPlaceholder(name: string): string {
  return `${name}.<timestamp>.bk`;
}

/**
 * Sequences a set of checksum-driven rename candidates (spec: user
 * request) into an ordered list of atomic, individually-safe rename
 * steps — handling the case where candidates form a CHAIN (X should
 * become Y, Y should become Z, ...) or a CYCLE (X should become Y and Y
 * should become X — a swap — or longer loops of the same shape).
 *
 * A chain is processed tail-first (the last hop moves first, freeing the
 * slot the previous hop needs), with one leading backup step only if the
 * chain's final destination is already occupied by some UNRELATED file
 * (not itself part of any candidate).
 *
 * A cycle can't be processed directly — every node's slot is occupied by
 * something that itself needs to move first, all the way around the loop.
 * Broken by backing up exactly one node first, then processing the rest
 * as a chain, with the final step sourced from that backup instead of the
 * (now renamed-away) original.
 *
 * Each candidate's own `leftName` is unique (drawn from a distinct
 * checksum) and so is each `rightName` (same reasoning on the other
 * side) — so the graph these candidates form has at most one outgoing and
 * one incoming edge per name, meaning it's always exactly a disjoint set
 * of simple chains and cycles, never anything more tangled.
 */
export function buildRenamePlan(
  candidates: RenamePlanCandidate[],
  existingLeftNames: ReadonlySet<string>,
): RenamePlanStep[] {
  const sorted = [...candidates].sort((a, b) =>
    a.leftName.localeCompare(b.leftName),
  );
  const rightNameFor = new Map(sorted.map((c) => [c.leftName, c.rightName]));
  const isIncoming = new Set(sorted.map((c) => c.rightName));

  const visited = new Set<string>();
  const steps: RenamePlanStep[] = [];

  // Chains: start from every leftName that is NOT itself some other
  // candidate's rightName (a "pure source" — nothing needs to move out of
  // ITS slot before this chain can start).
  for (const candidate of sorted) {
    if (visited.has(candidate.leftName) || isIncoming.has(candidate.leftName))
      continue;

    const chain: string[] = [candidate.leftName];
    let current = candidate.leftName;
    for (;;) {
      const next = rightNameFor.get(current)!;
      chain.push(next);
      visited.add(current);
      if (!rightNameFor.has(next)) break;
      current = next;
    }

    const sink = chain[chain.length - 1];
    if (existingLeftNames.has(sink)) {
      steps.push({
        sourceName: sink,
        destinationName: backupPlaceholder(sink),
        isBackup: true,
      });
    }
    for (let i = chain.length - 2; i >= 0; i--) {
      steps.push({
        sourceName: chain[i],
        destinationName: chain[i + 1],
        isBackup: false,
      });
    }
  }

  // Cycles: whatever's left unvisited only has neighbors among itself —
  // every remaining name has both an outgoing and an incoming edge.
  for (const candidate of sorted) {
    if (visited.has(candidate.leftName)) continue;

    const cycle: string[] = [candidate.leftName];
    let current = rightNameFor.get(candidate.leftName)!;
    while (current !== candidate.leftName) {
      cycle.push(current);
      visited.add(current);
      current = rightNameFor.get(current)!;
    }
    visited.add(candidate.leftName);

    const last = cycle[cycle.length - 1];
    const backupStepIndex = steps.length;
    steps.push({
      sourceName: last,
      destinationName: backupPlaceholder(last),
      isBackup: true,
    });
    for (let i = cycle.length - 2; i >= 0; i--) {
      steps.push({
        sourceName: cycle[i],
        destinationName: cycle[i + 1],
        isBackup: false,
      });
    }
    steps.push({
      sourceName: { dependsOnStepIndex: backupStepIndex },
      destinationName: cycle[0],
      isBackup: false,
    });
  }

  return steps;
}
